SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

CREATE EXTENSION IF NOT EXISTS "pgsodium" WITH SCHEMA "pgsodium";

CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";

CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "pgjwt" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";

CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";

SET default_tablespace = '';

SET default_table_access_method = "heap";

CREATE TABLE "public"."evaluation_bionic" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "user_id" "uuid" NOT NULL,
    "schneller" smallint NOT NULL,
    "leichter" smallint NOT NULL,
    "textverstaendnis" smallint NOT NULL,
    "woerter_finden" smallint NOT NULL,
    "mehr_texte" smallint NOT NULL,
    "in_schule" smallint NOT NULL,
    "anmerkungen" "text"
);

ALTER TABLE "public"."evaluation_bionic" OWNER TO "postgres";

ALTER TABLE "public"."evaluation_bionic" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."evaluation_bionic_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE "public"."evaluation_personal" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "user_id" "uuid" NOT NULL,
    "freude_lesen" smallint NOT NULL,
    "haeufigkeit_lesen" smallint NOT NULL,
    "ziel_lesen" smallint NOT NULL,
    "textverstaendnis" smallint NOT NULL,
    "alter" "text"
);

ALTER TABLE "public"."evaluation_personal" OWNER TO "postgres";

ALTER TABLE "public"."evaluation_personal" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."evaluation_personal_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE "public"."questions_lehrerin" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "user_id" "uuid" NOT NULL,
    "gefuehle_beruf" smallint NOT NULL,
    "warum_lehrer" smallint NOT NULL,
    "oeffentlichkeit_meinung" smallint NOT NULL,
    "vorwurf_eltern" smallint NOT NULL,
    "internet" smallint NOT NULL
);

ALTER TABLE "public"."questions_lehrerin" OWNER TO "postgres";

ALTER TABLE "public"."questions_lehrerin" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."questions__id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE "public"."questions_empirie" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "user_id" "uuid" NOT NULL,
    "hauptunterschied_empirie_theorie" smallint NOT NULL,
    "wichtigste_methode_objektiv" smallint NOT NULL,
    "rolle_vorhersagen" smallint NOT NULL
);

ALTER TABLE "public"."questions_empirie" OWNER TO "postgres";

ALTER TABLE "public"."questions_empirie" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."questions_empirie_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE "public"."questions_schwimmen" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "user_id" "uuid" NOT NULL,
    "ziel_hilfsprojekt" smallint NOT NULL,
    "ziel_turnier" smallint NOT NULL,
    "einnahmen_abhaengigkeit" smallint NOT NULL,
    "feststellung_lehrer" smallint NOT NULL,
    "grund_wiederholung" smallint NOT NULL,
    "rolle_lehrer" smallint NOT NULL
);

ALTER TABLE "public"."questions_schwimmen" OWNER TO "postgres";

ALTER TABLE "public"."questions_schwimmen" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."questions_schwimmen_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE "public"."tracking" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "user_id" "uuid" NOT NULL,
    "data" "jsonb" NOT NULL
);

ALTER TABLE "public"."tracking" OWNER TO "postgres";

ALTER TABLE "public"."tracking" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."tracking_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE "public"."users" (
    "id" "uuid" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "fingerprint" character varying NOT NULL,
    "test" boolean NOT NULL
);

ALTER TABLE "public"."users" OWNER TO "postgres";

ALTER TABLE ONLY "public"."evaluation_bionic"
    ADD CONSTRAINT "evaluation_bionic_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."evaluation_personal"
    ADD CONSTRAINT "evaluation_personal_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."evaluation_personal"
    ADD CONSTRAINT "evaluation_personal_user_id_key" UNIQUE ("user_id");

ALTER TABLE ONLY "public"."questions_lehrerin"
    ADD CONSTRAINT "questions__pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."questions_empirie"
    ADD CONSTRAINT "questions_empirie_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."questions_empirie"
    ADD CONSTRAINT "questions_empirie_user_id_key" UNIQUE ("user_id");

ALTER TABLE ONLY "public"."questions_schwimmen"
    ADD CONSTRAINT "questions_schwimmen_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."tracking"
    ADD CONSTRAINT "tracking_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."tracking"
    ADD CONSTRAINT "tracking_user_id_key" UNIQUE ("user_id");

ALTER TABLE ONLY "public"."users"
    ADD CONSTRAINT "users_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."evaluation_bionic"
    ADD CONSTRAINT "evaluation_bionic_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."evaluation_personal"
    ADD CONSTRAINT "evaluation_personal_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."questions_empirie"
    ADD CONSTRAINT "questions_empirie_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."questions_lehrerin"
    ADD CONSTRAINT "questions_lehrerin_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."questions_schwimmen"
    ADD CONSTRAINT "questions_schwimmen_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."tracking"
    ADD CONSTRAINT "tracking_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE CASCADE;

ALTER TABLE "public"."evaluation_bionic" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."evaluation_personal" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."questions_empirie" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."questions_lehrerin" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."questions_schwimmen" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."tracking" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."users" ENABLE ROW LEVEL SECURITY;

GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";

GRANT ALL ON TABLE "public"."evaluation_bionic" TO "anon";
GRANT ALL ON TABLE "public"."evaluation_bionic" TO "authenticated";
GRANT ALL ON TABLE "public"."evaluation_bionic" TO "service_role";

GRANT ALL ON SEQUENCE "public"."evaluation_bionic_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."evaluation_bionic_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."evaluation_bionic_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."evaluation_personal" TO "anon";
GRANT ALL ON TABLE "public"."evaluation_personal" TO "authenticated";
GRANT ALL ON TABLE "public"."evaluation_personal" TO "service_role";

GRANT ALL ON SEQUENCE "public"."evaluation_personal_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."evaluation_personal_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."evaluation_personal_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."questions_lehrerin" TO "anon";
GRANT ALL ON TABLE "public"."questions_lehrerin" TO "authenticated";
GRANT ALL ON TABLE "public"."questions_lehrerin" TO "service_role";

GRANT ALL ON SEQUENCE "public"."questions__id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."questions__id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."questions__id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."questions_empirie" TO "anon";
GRANT ALL ON TABLE "public"."questions_empirie" TO "authenticated";
GRANT ALL ON TABLE "public"."questions_empirie" TO "service_role";

GRANT ALL ON SEQUENCE "public"."questions_empirie_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."questions_empirie_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."questions_empirie_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."questions_schwimmen" TO "anon";
GRANT ALL ON TABLE "public"."questions_schwimmen" TO "authenticated";
GRANT ALL ON TABLE "public"."questions_schwimmen" TO "service_role";

GRANT ALL ON SEQUENCE "public"."questions_schwimmen_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."questions_schwimmen_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."questions_schwimmen_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."tracking" TO "anon";
GRANT ALL ON TABLE "public"."tracking" TO "authenticated";
GRANT ALL ON TABLE "public"."tracking" TO "service_role";

GRANT ALL ON SEQUENCE "public"."tracking_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."tracking_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."tracking_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."users" TO "anon";
GRANT ALL ON TABLE "public"."users" TO "authenticated";
GRANT ALL ON TABLE "public"."users" TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "service_role";

RESET ALL;
